### ISSUE TITLE
Occasionally leaderboard server times out, but still loads behind the error

### ISSUE THREAD

**Issue by 9thyear2** [fexed/Pinball-on-Android#62] opened 2022-08-22 01:48 UTC
![Screenshot_20220821-204414_Space_Cadet_Pinball](https://user-images.githubusercontent.com/29149297/185823179-ccd41bb5-95c9-4c39-8d24-13ebf2fb9b4a.png)

**Comment by fexed** [comment] 2023-03-03 13:30
I think I found the cause, should be fixed in v2.4 (coming in the future)

**Closed as completed** 2023-03-03 13:33 UTC
Labels: bug
