### ISSUE TITLE
Crash on skillshot 

### ISSUE THREAD

**Issue by Cytriix** [fexed/Pinball-on-Android#67] opened 2022-09-19 15:27 UTC
The game is crashing 1/10 times when you're doing a skillshot, at the exact moment when is supposed to make the skillshot announcement and sound.

**Comment by Go-rom** [comment] 2022-09-19 18:41
Duplicate of #52 i think

**Comment by Cytriix** [comment] 2022-09-19 18:43
True, haven't seen it

**Closed as not planned** 2022-09-19 18:43 UTC
